# Generated by Django 5.1.3 on 2024-12-01 14:28

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='شعبه صدور قرارداد')),
                ('policyholder', models.CharField(blank=True, max_length=100, null=True, verbose_name='بیمه گزار')),
                ('template_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره الگوی قرارداد')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد')),
                ('rasa_contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد سامانه')),
                ('start_contract_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع قرارداد')),
                ('end_contract_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان قرارداد')),
                ('profile_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پروفایل')),
                ('interval', models.IntegerField(blank=True, null=True, verbose_name='بازه قرارداد')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='جمعیت بیمه شدگان ')),
                ('premium', models.IntegerField(blank=True, null=True, verbose_name='حق بیمه')),
                ('recoverable_income_in_month', models.IntegerField(blank=True, null=True, verbose_name='میانگین درآمد قابل وصول یک ماه')),
                ('recovered_income', models.IntegerField(blank=True, null=True, verbose_name='درآمد وصول شده')),
                ('marketer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم بازاریاب')),
                ('marketer_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد بازاریاب')),
                ('wage_rate', models.IntegerField(blank=True, null=True, verbose_name='درصد بازاریابی')),
                ('wage', models.IntegerField(blank=True, null=True, verbose_name='کارمزد ماهیانه')),
                ('portfolio', models.CharField(blank=True, max_length=100, null=True, verbose_name='پرتفو')),
                ('is_active_contract', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیر فعال')),
                ('creation_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ایجاد قرارداد')),
                ('last_edition_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
