# Generated by Django 5.1.3 on 2024-12-01 15:51

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracts',
            options={'verbose_name': 'قرارداد', 'verbose_name_plural': 'قراردادها'},
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='last_edition_date',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='marketer_code',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='marketer_name',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='recoverable_income_in_month',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='recovered_income',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='wage',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='wage_rate',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='is_active_contract',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعال/غیر فعال'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='جمعیت بیمه\u200cشدگان'),
        ),
        migrations.CreateModel(
            name='PremiumCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_collected', models.IntegerField(verbose_name='مقدار حق بیمه وصول\u200cشده')),
                ('collection_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ وصول')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_collections', to='myapp.contracts')),
            ],
            options={
                'verbose_name': 'وصول حق بیمه',
                'verbose_name_plural': 'وصول\u200cهای حق بیمه',
            },
        ),
    ]
