# Generated by Django 5.1.3 on 2024-12-17 19:27

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_premiumcollection_collection_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumcollection',
            name='collection_date2',
        ),
        migrations.AlterField(
            model_name='premiumcollection',
            name='collection_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ وصول اتوماتیک'),
        ),
    ]
